function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#", "hide_level_select")  -- [1]
	self.active = false
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show_level_select") then                     -- [2]
		msg.post("#", "enable")

		self.active = true
	elseif message_id == hash("hide_level_select") then                 -- [3]
		msg.post("#", "disable")

		self.active = false
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed and self.active then
		for n = 1, 4 do
			local button_level = gui.get_node("button_level_" .. n)

			if gui.pick_node(button_level, action.x, action.y) then
				msg.post("/loader#loader", "load_level", { level = n })
				msg.post("#level_select", "hide_level_select")
			end
		end

		--- Add these lines:
		local button_back = gui.get_node("button_back")         -- [1]

		if gui.pick_node(button_back, action.x, action.y) then
			msg.post("#level_select", "hide_level_select")
			msg.post("#start", "show_start")
		end
		---
	end
end