function on_message(self, message_id, message, sender)
	if message_id == hash("level_completed") then                       -- [1]
		local well_done_message = gui.get_node("well_done_message")

		gui.animate(well_done_message, "position.x", 320, gui.EASING_OUTSINE, 1, 1.5)
	end
end

function on_input(self, action_id, action)                              -- [2]
	if action_id == hash("touch") and action.pressed then
		local button_back = gui.get_node("button_back")

		if gui.pick_node(button_back, action.x, action.y) then
			msg.post("default:/guis#level_select", "show_level_select") -- [3]
			msg.post("default:/loader#loader", "unload_level")
		end

		local button_next = gui.get_node("button_next")

		if gui.pick_node(button_next, action.x, action.y) then
			msg.post("default:/loader#loader", "next_level")            -- [4]
		end
	end
end