function init(self)
	msg.post(".", "acquire_input_focus")

	-- Add this line:
	self.current_level = 0	-- [1]
end

function on_message(self, message_id, message, sender)
	if message_id == hash("load_level") then
		-- Add this line:
		self.current_level = message.level	-- [2]

		local proxy = "#proxy_level_" .. message.level
		msg.post(proxy, "load")

		-- Add these lines:
	elseif message_id == hash("next_level") then                        -- [3]
		msg.post("#", "unload_level")
		msg.post("#", "load_level", { level = self.current_level + 1 })
	elseif message_id == hash("unload_level") then                      -- [4]
		local proxy = "#proxy_level_" .. self.current_level

		msg.post(proxy, "disable")
		msg.post(proxy, "final")
		msg.post(proxy, "unload")
		--

	elseif message_id == hash("proxy_loaded") then
		msg.post(sender, "init")
		msg.post(sender, "enable")
	end
end