function init(self)
	msg.post("#", "show_start")                                         -- [1]

	self.active = false
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show_start") then                            -- [2]
		msg.post("#", "enable")

		self.active = true
	elseif message_id == hash("hide_start") then
		msg.post("#", "disable")

		self.active = false
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed and self.active then
		local start_button = gui.get_node("button_start")

		if gui.pick_node(start_button, action.x, action.y) then          -- [3]
			msg.post("#", "hide_start")
			msg.post("#level_select", "show_level_select")
		end
	end
end